### ISSUE TITLE
parse_headers is ignoring the Content-Type

### ISSUE THREAD

**Issue by kbrannen** [clapautius/mhtml-tool#1]
There is bad logic in parse_headers() where it reads a line ahead but then doesn't use it or something like that. I've been able to fix it. Do you want a pull request for this or not? Since the project hasn't been touched in 4 years, do you even still care about it?

There's at least 1 other issue, but I'll wait to hear from you on this before I report it.

BTW, thanks for writing this. Even with the bugs it generally gets the job done and I can probably fix the bugs.

**Comment by clapautius** [comment]
Hi,

**Comment by clapautius** [comment]
Hi,

Yes, please create a pull request.

Although I'm not using this script anymore, I do have some mhtml documents, so I would like to have a stable, bug-free tool. 😉

Thanks.
